### ISSUE TITLE
Add Configuration Examples and Integration Tests

### ISSUE THREAD

**Issue by ashmortar** [ephlabs/eph#39]
## Description
Create comprehensive examples and integration tests for the configuration system.

### Example Configurations
Create example YAML files in `configs/examples/`:

1. **minimal.yaml** - Bare minimum valid configuration
2. **kubernetes-basic.yaml** - Simple Kubernetes deployment
3. **kubernetes-advanced.yaml** - All Kubernetes features
4. **multi-provider.yaml** - Primary and fallback providers
5. **database-setup.yaml** - Database configuration examples
6. **security-examples.yaml** - Various security configurations
7. **image-resolution.yaml** - Different image resolution strategies

### Integration Tests
Write tests that use complete real-world configurations:
- Load and validate each example
- Test common configuration patterns
- Verify error messages for common mistakes
- Performance tests for large configurations

### Documentation
Create `docs/configuration.md` with:
- Configuration overview
- Field-by-field reference
- Common patterns and recipes
- Troubleshooting guide
- Migration guide from other tools

### minimal.yaml
```yaml
version: "1.0"
name: my-app

triggers:
  - type: pr_label
    labels: ["preview"]

environment:
  images:
    - name: app
      repository: ghcr.io/myorg/myapp
      tag_template: "pr-{pr_number}"
```

### kubernetes-advanced.yaml
```yaml
version: "1.0"
name: complex-app

providers:
  primary: kubernetes
  fallback: docker-compose

triggers:
  - type: pr_label
    labels: ["preview", "eph:deploy"]
    wait_for_checks: ["build", "test"]
  - type: pr_comment
    patterns: ["/deploy", "/preview"]

environment:
  name_template: "{project}-{words}-{number}"
  ttl: 72h
  idle_timeout: 4h
  wake_on_access: true
  
  resources:
    cpu_request: "100m"
    cpu_limit: "2"
    memory_request: "128Mi"
    memory_limit: "4Gi"
  
  images:
    - name: api
      repository: ghcr.io/myorg/api
      tag_template: "pr-{pr_number}-{commit_sha:0:7}"
      max_age: 7d
      fallback_tag: "latest"
      fallback_behavior: "wait"
    
    - name: frontend
      repository: ghcr.io/myorg/frontend
      tag_pattern: "pr-{pr_number}-*"

kubernetes:
  context: "${K8S_CONTEXT}"
  namespace_template: "{project}-pr-{pr_number}"
  
  manifests:
    - path: ./k8s/base
    - kustomization: ./k8s/overlays/preview
      patches:
        - target:
            kind: Deployment
            name: api
          patch: |
            - op: replace
              path: /spec/replicas
              value: 1
  
  ingress:
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

database:
  enabled: true
  instances:
    - name: main
      type: postgres
      version: "15"
      template:
        strategy: seed
        seed:
          scripts:
            - ./db/schema.sql
            - ./db/seed-data.sql

security:
  environment_access:
    default: public
  naming:
    strategy: readable
    include_project: true
```

## Files to Create
- `configs/examples/*.yaml` - Example configurations
- `internal/config/integration_test.go` - Integration tests
- `docs/configuration.md` - User documentation
- `internal/config/examples_test.go` - Validate all examples

## Acceptance Criteria
- [ ] At least 7 example configurations
- [ ] Each example has comments explaining usage
- [ ] Integration tests cover all examples
- [ ] Documentation is comprehensive and clear
- [ ] Common mistakes have test cases
- [ ] Performance benchmarks included
- [ ] All examples actually work

## Dependencies
This issue should be done after:
- #38 (Complete configuration loading)

This completes the configuration system implementation.
