### ISSUE TITLE
Update README with Runner Architecture

### ISSUE THREAD

**Issue by ashmortar** [ephlabs/eph#41]
## Description
Update README.md to reflect the new control/data plane architecture with runners, removing all template references and showing the explicit configuration approach.

## Scope
Replace the current Architecture section and add new Installation section to reflect the runner-based approach.

#### 1. Replace Architecture Section
```markdown
## Architecture

Eph uses a split control/data plane architecture for security and flexibility:

```mermaid
graph TB
    subgraph "Control Plane (SaaS or Self-Hosted)"
        API[REST API]
        Auth[Auth & Tokens]
        Reconciler[Reconciler]
        Webhooks[Webhook Handler]
    end
    
    subgraph "Data Plane (Your Infrastructure)"
        Runner[eph-runner]
        K8s[Kubernetes]
        Registry[Container Registry]
    end
    
    Runner -->|Poll for desired state| API
    API -->|Environment list| Runner
    Runner --> K8s
    Runner --> Registry
```

**Key Benefits**:
- **Security**: Your credentials never leave your infrastructure  
- **Efficient**: ETag-based polling reduces bandwidth and load
- **Flexibility**: Use Eph Cloud or self-host the control plane
- **Stateless**: Runners require no persistent state
```

#### 2. Add Installation Section
```markdown
## Installation

### Eph Cloud (SaaS)

1. **Sign up for free account**
   ```bash
   eph auth signup
   ```

2. **Install runner in your cluster**
   ```bash
   eph runner install --token <token> | kubectl apply -f -
   ```

3. **Start creating environments**
   ```bash
   eph list
   ```

### Self-Hosted

See [docs/self-hosted.md](docs/self-hosted.md) for detailed instructions.
```

#### 3. Update Configuration Section
Remove all template references and show explicit manifest configuration:

```markdown
## Configuration

Projects configure Eph via `eph.yaml`:

```yaml
version: "1.0"
name: my-app

triggers:
  - pr_label: preview

kubernetes:
  # Reference your existing Kubernetes manifests
  manifests:
    - ./k8s/deployment.yaml
    - ./k8s/service.yaml
  
  # Apply overrides for preview environments
  overrides:
    - image_tag: "pr-{pr_number}"
    - replicas: 1
```

Generate your initial configuration:
```bash
eph init --from-kubernetes ./k8s
```
```

## Files to Modify
- `README.md` - Complete rewrite of Architecture and Configuration sections

## Acceptance Criteria
- [ ] Architecture diagram updated to show control/data plane split
- [ ] Installation instructions clear for both SaaS and self-hosted
- [ ] Configuration examples use new explicit manifest format
- [ ] No references to templates remain
- [ ] Links to new documentation files work
- [ ] Mermaid diagram renders correctly on GitHub

## Labels
`documentation`, `foundation`

## Phase
1-Documentation

## Priority  
P0 (High)
