### ISSUE TITLE
Update Architecture Plan with Runner Design

### ISSUE THREAD

**Issue by ashmortar** [ephlabs/eph#42]
## Description
Update `architecture-plan.md` to document the control/data plane split and runner details, removing template references and establishing the new architecture philosophy.

## Scope
Add comprehensive documentation of the runner architecture after the "Reconciliation Philosophy" section.

#### 1. Control Plane / Data Plane Split
```markdown
## Control Plane / Data Plane Split

Eph adopts a split architecture similar to Kubernetes itself and modern GitOps tools:

### Control Plane Responsibilities
- **Decision Making**: What environments should exist based on Git state
- **Reconciliation**: Polls GitHub/GitLab to determine desired state
- **API Gateway**: Providing REST API for CLI and runners
- **Authentication**: Managing API tokens and user auth
- **Webhook Processing**: Receiving events from GitHub/GitLab
- **Multi-tenancy**: Isolating organizations in SaaS mode

PostgreSQL is used ONLY for:
- API tokens and authentication
- Event logs and audit trails  
- Usage metrics and analytics
- NEVER for environment state (Git is the source of truth)

### Data Plane Responsibilities  
- **Execution**: Creating/updating/deleting actual environments
- **Provider Interface**: Talking to Kubernetes, Docker, cloud providers
- **Secret Management**: Using local credentials for deployments
- **Status Reporting**: Informing control plane of actual state

### Security Benefits

This split provides critical security advantages:

1. **Credential Isolation**: Provider credentials never leave user's infrastructure
2. **Network Security**: Runner only makes outbound HTTPS connections
3. **Blast Radius**: Compromise of SaaS control plane cannot access user workloads
4. **Compliance**: Sensitive data remains in user's security boundary
```

#### 2. Runner Architecture
```markdown
## Runner Architecture

### Outbound-Only Design

Runners are designed to work in the most restrictive network environments:

- **No Inbound Connections**: Runners poll the control plane
- **HTTPS Only**: Standard port 443 outbound
- **Firewall Friendly**: Works behind NAT, corporate proxies
- **No VPN Required**: Direct internet connection sufficient

### Health Through Polling

The polling mechanism serves as the health check:

```go
// Every poll updates last seen time
func (h *Handler) GetDesiredState(w http.ResponseWriter, r *http.Request) {
    runnerID := r.Context().Value("runner_id").(uuid.UUID)
    h.updateLastSeen(runnerID)  // This IS the health check\!
    // ... return desired state
}
```

### ETag-Based Efficiency

```
Runner: GET /desired-state
        If-None-Match: "abc123"
        
Control: 304 Not Modified     (no changes)
   OR
Control: 200 OK               (changes detected)
         ETag: "def456"
         Body: [environments]
```

This provides:
- Minimal bandwidth usage
- Adaptive polling intervals
- Standard HTTP semantics
- CDN compatibility
```

#### 3. Update Configuration Schema
Replace the Configuration Schema section to remove templates and show explicit manifest references:

```markdown
## Configuration Schema

### No Templates, Only References

```yaml
version: "1.0"
name: my-app
triggers:
  - pr_label: preview

kubernetes:
  # REQUIRED: Where are your manifests?
  manifests:
    - ./k8s/deployment.yaml
    - ./k8s/service.yaml
    - ./k8s/ingress.yaml
  
  # OPTIONAL: Preview environment overrides
  overrides:
    - image_tag: "pr-{pr_number}"
    - replicas: 1
```

### Why No Templates?
- Generic templates are too generic to be useful
- Specific templates are too specific to be reusable
- Users already have working configs - use them\!
- Explicit is better than implicit
- Easier to debug when things go wrong
```

## Files to Modify
- `architecture-plan.md` - Add new sections after "Reconciliation Philosophy"

## Acceptance Criteria
- [ ] Control/data plane split explained clearly
- [ ] Runner architecture documented with code examples
- [ ] Security benefits highlighted
- [ ] Configuration examples updated to remove templates
- [ ] ETag polling mechanism documented
- [ ] No references to template system remain

## Labels
`documentation`, `foundation`

## Phase
1-Documentation

## Priority  
P0 (High)
